// src/pages/WorkOrders/WorkOrders.tsx
// BEL Smart Automation • NovaFlow — PWD Work Orders & Municipal Repair Pipeline

import React, { useState, useMemo } from "react";
import { Link } from "react-router-dom";
import {
  Wrench, FileText, CheckCircle2, Clock, AlertTriangle, Search,
  Filter, Download, Plus, ChevronRight, X, Printer, Check, UserCheck,
  Building2, MapPin, Calendar, Layers, ShieldCheck, ArrowRight, ArrowUpRight
} from "lucide-react";

export interface WorkOrderItem {
  id: string;
  defectId: string;
  hazardType: "POTHOLE" | "WATERLOGGING" | "DAMAGED_ROAD" | "CRACKS" | "ROAD_DEBRIS" | "DAMAGED_INFRA";
  title: string;
  location: string;
  city: "New Delhi" | "Bengaluru" | "Mumbai";
  severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
  agency: string;
  contractor: string;
  assignedCrew: string;
  createdAt: string;
  targetCompletion: string;
  status: "Pending" | "Assigned" | "In Progress" | "Completed";
  estimatedCost: string;
  notes: string;
  timeline: { step: string; timestamp: string; done: boolean }[];
}

const INITIAL_WORK_ORDERS: WorkOrderItem[] = [
  {
    id: "WO-BLR-2026-104",
    defectId: "HAZ-2026-081",
    hazardType: "POTHOLE",
    title: "Outer Ring Road Asphalt Milling & Cold-Patch Filling",
    location: "Outer Ring Road km 14.2, Near Marathahalli Flyover",
    city: "Bengaluru",
    severity: "CRITICAL",
    agency: "BBMP Road Infrastructure Division",
    contractor: "Apex InfraTech Solutions Ltd.",
    assignedCrew: "Rapid Repair Unit 04 (Lead: Eng. S. Ramesh)",
    createdAt: "2026-09-19 08:30",
    targetCompletion: "2026-09-19 18:00",
    status: "In Progress",
    estimatedCost: "₹ 48,500",
    notes: "Requires fast-setting polymeric asphalt compound. High bus traffic lane requires safety cones and traffic diversion during 14:00-16:00.",
    timeline: [
      { step: "AI Hazard Confirmed by 3 Buses", timestamp: "08:15 AM", done: true },
      { step: "Work Order Generated by NovaFlow", timestamp: "08:30 AM", done: true },
      { step: "Contractor Dispatched to Site", timestamp: "09:45 AM", done: true },
      { step: "Excavation & Bitumen Laying", timestamp: "11:20 AM", done: true },
      { step: "Compaction & Final Inspection", timestamp: "Est. 05:00 PM", done: false }
    ]
  },
  {
    id: "WO-DEL-2026-088",
    defectId: "HAZ-2026-082",
    hazardType: "WATERLOGGING",
    title: "AIIMS Flyover Underpass Storm Drain De-silting & Pump Deployment",
    location: "Ring Road near AIIMS Flyover Underpass Lane 2",
    city: "New Delhi",
    severity: "HIGH",
    agency: "Delhi PWD Drainage & Stormwater Cell",
    contractor: "Delhi Jal & Civic Works",
    assignedCrew: "Drainage Rapid Response Team 2",
    createdAt: "2026-09-19 09:10",
    targetCompletion: "2026-09-19 15:00",
    status: "In Progress",
    estimatedCost: "₹ 32,000",
    notes: "High-capacity submersible pump deployed to clear 14cm accumulated water. Silt trap cleaning underway.",
    timeline: [
      { step: "Telemetry Flagged Waterlogging", timestamp: "09:02 AM", done: true },
      { step: "Work Order Created", timestamp: "09:10 AM", done: true },
      { step: "Pump Truck Deployed", timestamp: "09:40 AM", done: true },
      { step: "Water Clearance Verification", timestamp: "Est. 02:30 PM", done: false }
    ]
  },
  {
    id: "WO-MUM-2026-052",
    defectId: "HAZ-2026-083",
    hazardType: "DAMAGED_ROAD",
    title: "Western Express Highway Concrete Spalling Rehabilitation",
    location: "Western Express Highway (Andheri Flyover Ramp 3)",
    city: "Mumbai",
    severity: "HIGH",
    agency: "NHAI Western Corridor Division",
    contractor: "L&T Heavy Civil Maintenance",
    assignedCrew: "Structural Highway Crew C-3",
    createdAt: "2026-09-19 07:45",
    targetCompletion: "2026-09-20 06:00",
    status: "Assigned",
    estimatedCost: "₹ 1,15,000",
    notes: "Night repair window approved. Epoxy injection and micro-concrete overlay scheduled for 23:00 tonight.",
    timeline: [
      { step: "Vision Defect Logged", timestamp: "07:30 AM", done: true },
      { step: "Work Order Created & Approved", timestamp: "07:45 AM", done: true },
      { step: "Contractor Work Permit Issued", timestamp: "10:15 AM", done: true },
      { step: "Night Shift Execution", timestamp: "Est. 11:00 PM", done: false }
    ]
  },
  {
    id: "WO-DEL-2026-089",
    defectId: "HAZ-2026-084",
    hazardType: "DAMAGED_INFRA",
    title: "Nehru Place Bus Shelter Fractured Beam & Solar Panel Hazard",
    location: "Nehru Place Bus Terminal Entry Bay 4",
    city: "New Delhi",
    severity: "MEDIUM",
    agency: "Delhi Transport Infrastructure Dev Corp (DTIDC)",
    contractor: "Civic Structures Ltd.",
    assignedCrew: "Metal Works & Safety Unit",
    createdAt: "2026-09-19 10:20",
    targetCompletion: "2026-09-20 18:00",
    status: "Pending",
    estimatedCost: "₹ 24,000",
    notes: "Pending structural engineer on-site signoff. Bay 4 barricaded with reflective warning tape.",
    timeline: [
      { step: "Camera Ingestion Detected Tilt", timestamp: "10:05 AM", done: true },
      { step: "Pending Approval from DTIDC", timestamp: "10:20 AM", done: true },
      { step: "Contractor Assignment", timestamp: "Pending", done: false }
    ]
  },
  {
    id: "WO-BLR-2026-102",
    defectId: "HAZ-2026-079",
    hazardType: "POTHOLE",
    title: "Hosur Road Junction Edge Repair & Resurfacing",
    location: "Hosur Road Silk Board Junction Ramp A",
    city: "Bengaluru",
    severity: "CRITICAL",
    agency: "BBMP Road Infrastructure Division",
    contractor: "Apex InfraTech Solutions Ltd.",
    assignedCrew: "Unit 01 (Lead: Eng. A. Joshi)",
    createdAt: "2026-09-18 14:15",
    targetCompletion: "2026-09-18 22:00",
    status: "Completed",
    estimatedCost: "₹ 54,000",
    notes: "Full depth mastic asphalt compaction complete. Verified by subsequent Bus #04 and Bus #12 passes with 0mm defect depth.",
    timeline: [
      { step: "Defect Identified", timestamp: "Sep 18, 02:00 PM", done: true },
      { step: "WO Dispatched", timestamp: "Sep 18, 02:30 PM", done: true },
      { step: "Repair Completed & Inspected", timestamp: "Sep 18, 08:45 PM", done: true },
      { step: "Closed & Re-verified by Bus Pass", timestamp: "Sep 18, 09:30 PM", done: true }
    ]
  },
  {
    id: "WO-MUM-2026-050",
    defectId: "HAZ-2026-078",
    hazardType: "ROAD_DEBRIS",
    title: "Eastern Freeway Spilled Gravel & Metal Obstacle Clearance",
    location: "Eastern Freeway Southbound km 8.1",
    city: "Mumbai",
    severity: "HIGH",
    agency: "MCGM Disaster Management & Road Maintenance",
    contractor: "Mumbai Quick Clear Corp",
    assignedCrew: "Expressway Sweeper Crew 2",
    createdAt: "2026-09-18 16:30",
    targetCompletion: "2026-09-18 19:00",
    status: "Completed",
    estimatedCost: "₹ 18,000",
    notes: "Industrial road sweeper cleared 220kg of fallen construction gravel. Normal speed restored within 90 minutes.",
    timeline: [
      { step: "Debris Detected by Bus Dashcam", timestamp: "Sep 18, 04:20 PM", done: true },
      { step: "Crew Dispatched", timestamp: "Sep 18, 04:35 PM", done: true },
      { step: "Highway Cleared & Normalized", timestamp: "Sep 18, 05:55 PM", done: true }
    ]
  },
  {
    id: "WO-DEL-2026-085",
    defectId: "HAZ-2026-075",
    hazardType: "CRACKS",
    title: "Vikas Marg Longitude Fatigue Cracking Bitumen Sealing",
    location: "Vikas Marg near Laxmi Nagar Metro Station",
    city: "New Delhi",
    severity: "LOW",
    agency: "Delhi PWD East Zone",
    contractor: "Apex Road Services",
    assignedCrew: "Crack Sealing Unit 3",
    createdAt: "2026-09-19 11:00",
    targetCompletion: "2026-09-21 17:00",
    status: "Pending",
    estimatedCost: "₹ 28,000",
    notes: "Thermal crack sealing scheduled for off-peak weekend hours.",
    timeline: [
      { step: "Crack Severity Profiled", timestamp: "10:45 AM", done: true },
      { step: "Pending Work Allocation", timestamp: "11:00 AM", done: true }
    ]
  }
];

export const WorkOrders: React.FC = () => {
  const [workOrders, setWorkOrders] = useState<WorkOrderItem[]>(INITIAL_WORK_ORDERS);
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("ALL");
  const [agencyFilter, setAgencyFilter] = useState<string>("ALL");
  const [severityFilter, setSeverityFilter] = useState<string>("ALL");

  // Selected Order for Modal
  const [selectedOrder, setSelectedOrder] = useState<WorkOrderItem | null>(null);

  // Report Modal State
  const [showReportModal, setShowReportModal] = useState(false);
  const [reportAgency, setReportAgency] = useState("ALL");
  const [reportDateRange, setReportDateRange] = useState("Last 7 Days");
  const [reportStatus, setReportStatus] = useState("ALL");
  const [reportDownloaded, setReportDownloaded] = useState(false);

  // New Work Order Modal
  const [showNewOrderModal, setShowNewOrderModal] = useState(false);
  const [newTitle, setNewTitle] = useState("");
  const [newLocation, setNewLocation] = useState("");
  const [newAgency, setNewAgency] = useState("Delhi PWD");
  const [newSeverity, setNewSeverity] = useState<"CRITICAL" | "HIGH" | "MEDIUM" | "LOW">("HIGH");

  // Filtered Orders
  const filteredOrders = useMemo(() => {
    return workOrders.filter((order) => {
      const matchesSearch =
        order.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
        order.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        order.location.toLowerCase().includes(searchQuery.toLowerCase()) ||
        order.contractor.toLowerCase().includes(searchQuery.toLowerCase());

      const matchesStatus = statusFilter === "ALL" || order.status === statusFilter;
      const matchesAgency = agencyFilter === "ALL" || order.agency.toLowerCase().includes(agencyFilter.toLowerCase());
      const matchesSeverity = severityFilter === "ALL" || order.severity === severityFilter;

      return matchesSearch && matchesStatus && matchesAgency && matchesSeverity;
    });
  }, [workOrders, searchQuery, statusFilter, agencyFilter, severityFilter]);

  // Counts for KPIs
  const counts = useMemo(() => {
    return {
      total: 126, // Official total pipeline
      pending: workOrders.filter(w => w.status === "Pending").length + 14,
      assigned: workOrders.filter(w => w.status === "Assigned").length + 30,
      inProgress: workOrders.filter(w => w.status === "In Progress").length + 38,
      completed: workOrders.filter(w => w.status === "Completed").length + 36,
    };
  }, [workOrders]);

  const handleUpdateStatus = (id: string, newStatus: "Pending" | "Assigned" | "In Progress" | "Completed") => {
    setWorkOrders(prev => prev.map(item => {
      if (item.id === id) {
        return {
          ...item,
          status: newStatus,
          timeline: [
            ...item.timeline,
            { step: `Status updated to ${newStatus}`, timestamp: "Just now", done: true }
          ]
        };
      }
      return item;
    }));
    if (selectedOrder && selectedOrder.id === id) {
      setSelectedOrder(prev => prev ? { ...prev, status: newStatus } : null);
    }
  };

  const handleCreateWorkOrder = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle || !newLocation) return;

    const newId = `WO-GEN-${Math.floor(100 + Math.random() * 900)}`;
    const newEntry: WorkOrderItem = {
      id: newId,
      defectId: `HAZ-NEW-${Math.floor(100 + Math.random() * 900)}`,
      hazardType: "POTHOLE",
      title: newTitle,
      location: newLocation,
      city: "New Delhi",
      severity: newSeverity,
      agency: newAgency,
      contractor: "Municipal PWD Fast Track Crew",
      assignedCrew: "Dispatched Squad #5",
      createdAt: new Date().toISOString().substring(0, 16).replace("T", " "),
      targetCompletion: "Within 24 Hours",
      status: "Assigned",
      estimatedCost: "₹ 35,000",
      notes: "Direct manual command dispatch initiated via Urban Fleet Intelligence Dashboard.",
      timeline: [
        { step: "Manual Dispatch Order Created", timestamp: "Just now", done: true },
        { step: "SLA Tracker Activated", timestamp: "Just now", done: true }
      ]
    };

    setWorkOrders([newEntry, ...workOrders]);
    setShowNewOrderModal(false);
    setNewTitle("");
    setNewLocation("");
  };

  const handleDownloadCsv = () => {
    const headers = "Work Order ID,Defect ID,Hazard Type,Title,Location,City,Severity,Agency,Contractor,Status,Estimated Cost\n";
    const rows = filteredOrders.map(o => 
      `"${o.id}","${o.defectId}","${o.hazardType}","${o.title}","${o.location}","${o.city}","${o.severity}","${o.agency}","${o.contractor}","${o.status}","${o.estimatedCost}"`
    ).join("\n");

    const blob = new Blob([headers + rows], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `PWD_Work_Orders_${new Date().toISOString().slice(0, 10)}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="min-h-full pb-16 bg-[#F8FAFC]">
      {/* Top Breadcrumb & Page Banner */}
      <div className="bg-[#1B254B] border-b border-[#2D3A6E] text-white px-4 sm:px-6 lg:px-8 py-5">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-[#93C5FD] mb-1.5">
              <Building2 className="w-3.5 h-3.5 text-[#60A5FA]" />
              <span>Bharat Electronics Limited (BEL) • Municipal Repair Pipeline</span>
            </div>
            <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold tracking-tight text-white flex items-center gap-2.5">
              <Wrench className="w-7 h-7 text-[#F59E0B]" />
              PWD Work Orders Management
            </h1>
            <p className="text-sm text-[#94A3B8] mt-1">
              End-to-end municipal repair workflow connecting bus-detected road hazards directly to PWD, BBMP, and NHAI field teams.
            </p>
          </div>

          {/* Action CTAs */}
          <div className="flex flex-wrap items-center gap-2.5">
            <button
              onClick={() => setShowReportModal(true)}
              className="inline-flex items-center gap-2 px-3.5 py-2 rounded-md bg-[#2D3A6E] hover:bg-[#3B4C8C] text-white text-xs sm:text-sm font-medium transition border border-[#475569] shadow-sm"
            >
              <FileText className="w-4 h-4 text-[#93C5FD]" />
              <span>Generate PWD Report</span>
            </button>

            <button
              onClick={() => setShowNewOrderModal(true)}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-md bg-[#2563EB] hover:bg-[#1D4ED8] text-white text-xs sm:text-sm font-semibold transition shadow-sm"
            >
              <Plus className="w-4 h-4" />
              <span>Create Work Order</span>
            </button>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-6">
        {/* KPI Strip */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3.5 mb-6">
          <div className="bg-white border border-[#CBD5E1] rounded-lg p-4 shadow-sm">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold uppercase tracking-wider text-[#64748B]">Total Orders</span>
              <FileText className="w-4 h-4 text-[#64748B]" />
            </div>
            <div className="mt-2 text-2xl font-black text-[#1E293B]">{counts.total}</div>
            <p className="text-[11px] text-[#059669] font-medium mt-0.5">↑ 14 added today</p>
          </div>

          <div className="bg-white border border-[#CBD5E1] rounded-lg p-4 shadow-sm">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold uppercase tracking-wider text-[#D97706]">Pending Review</span>
              <Clock className="w-4 h-4 text-[#D97706]" />
            </div>
            <div className="mt-2 text-2xl font-black text-[#D97706]">{counts.pending}</div>
            <p className="text-[11px] text-[#64748B] font-medium mt-0.5">Awaiting assignment</p>
          </div>

          <div className="bg-white border border-[#CBD5E1] rounded-lg p-4 shadow-sm">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold uppercase tracking-wider text-[#2563EB]">Assigned</span>
              <UserCheck className="w-4 h-4 text-[#2563EB]" />
            </div>
            <div className="mt-2 text-2xl font-black text-[#2563EB]">{counts.assigned}</div>
            <p className="text-[11px] text-[#64748B] font-medium mt-0.5">Contractor allocated</p>
          </div>

          <div className="bg-white border border-[#CBD5E1] rounded-lg p-4 shadow-sm">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold uppercase tracking-wider text-[#7C3AED]">In Progress</span>
              <Wrench className="w-4 h-4 text-[#7C3AED]" />
            </div>
            <div className="mt-2 text-2xl font-black text-[#7C3AED]">{counts.inProgress}</div>
            <p className="text-[11px] text-[#64748B] font-medium mt-0.5">Crews on-site</p>
          </div>

          <div className="bg-white border border-[#CBD5E1] rounded-lg p-4 shadow-sm col-span-2 sm:col-span-1">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold uppercase tracking-wider text-[#059669]">Completed</span>
              <CheckCircle2 className="w-4 h-4 text-[#059669]" />
            </div>
            <div className="mt-2 text-2xl font-black text-[#059669]">{counts.completed}</div>
            <p className="text-[11px] text-[#059669] font-medium mt-0.5">Verified by bus re-pass</p>
          </div>
        </div>

        {/* Filters & Search Toolbar */}
        <div className="bg-white border border-[#CBD5E1] rounded-lg p-4 shadow-sm mb-6">
          <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-3.5">
            {/* Search */}
            <div className="relative flex-1 min-w-[240px]">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#94A3B8]" />
              <input
                type="text"
                placeholder="Search Work Order ID, road location, contractor, or issue..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-9 pr-3.5 py-2 text-sm border border-[#CBD5E1] rounded-md focus:outline-none focus:ring-2 focus:ring-[#2563EB] focus:border-transparent text-[#1E293B]"
              />
            </div>

            {/* Dropdown Filters */}
            <div className="flex flex-wrap items-center gap-2.5">
              {/* Status Filter */}
              <div className="flex items-center gap-1.5 text-xs">
                <span className="text-[#64748B] font-medium">Status:</span>
                <select
                  value={statusFilter}
                  onChange={(e) => setStatusFilter(e.target.value)}
                  className="px-2.5 py-1.5 text-xs font-semibold border border-[#CBD5E1] rounded-md bg-[#F8FAFC] text-[#1E293B] focus:outline-none focus:ring-2 focus:ring-[#2563EB]"
                >
                  <option value="ALL">All Statuses</option>
                  <option value="Pending">Pending Review</option>
                  <option value="Assigned">Assigned</option>
                  <option value="In Progress">In Progress</option>
                  <option value="Completed">Completed</option>
                </select>
              </div>

              {/* Agency Filter */}
              <div className="flex items-center gap-1.5 text-xs">
                <span className="text-[#64748B] font-medium">Agency:</span>
                <select
                  value={agencyFilter}
                  onChange={(e) => setAgencyFilter(e.target.value)}
                  className="px-2.5 py-1.5 text-xs font-semibold border border-[#CBD5E1] rounded-md bg-[#F8FAFC] text-[#1E293B] focus:outline-none focus:ring-2 focus:ring-[#2563EB]"
                >
                  <option value="ALL">All Agencies</option>
                  <option value="BBMP">BBMP (Bengaluru)</option>
                  <option value="Delhi PWD">Delhi PWD</option>
                  <option value="NHAI">NHAI National Highways</option>
                  <option value="MCGM">MCGM (Mumbai)</option>
                </select>
              </div>

              {/* Severity Filter */}
              <div className="flex items-center gap-1.5 text-xs">
                <span className="text-[#64748B] font-medium">Severity:</span>
                <select
                  value={severityFilter}
                  onChange={(e) => setSeverityFilter(e.target.value)}
                  className="px-2.5 py-1.5 text-xs font-semibold border border-[#CBD5E1] rounded-md bg-[#F8FAFC] text-[#1E293B] focus:outline-none focus:ring-2 focus:ring-[#2563EB]"
                >
                  <option value="ALL">All Severities</option>
                  <option value="CRITICAL">Critical</option>
                  <option value="HIGH">High</option>
                  <option value="MEDIUM">Medium</option>
                  <option value="LOW">Low</option>
                </select>
              </div>

              {/* Download CSV */}
              <button
                onClick={handleDownloadCsv}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold border border-[#CBD5E1] rounded-md bg-white hover:bg-[#F1F5F9] text-[#1E293B] transition"
                title="Export current table to CSV"
              >
                <Download className="w-3.5 h-3.5 text-[#2563EB]" />
                <span>Export CSV</span>
              </button>
            </div>
          </div>
        </div>

        {/* Work Orders Table */}
        <div className="bg-white border border-[#CBD5E1] rounded-lg shadow-sm overflow-hidden">
          <div className="px-4 py-3.5 border-b border-[#E2E8F0] flex items-center justify-between bg-[#F8FAFC]">
            <div className="flex items-center gap-2">
              <span className="text-sm font-bold text-[#1E293B]">Active Repair Pipeline</span>
              <span className="px-2 py-0.5 text-xs font-semibold rounded-full bg-[#E2E8F0] text-[#475569]">
                {filteredOrders.length} records
              </span>
            </div>
            <span className="text-xs text-[#64748B]">Showing verified transit defect work orders</span>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm text-[#1E293B]">
              <thead className="text-[11px] font-bold uppercase tracking-wider bg-[#F1F5F9] text-[#475569] border-b border-[#CBD5E1]">
                <tr>
                  <th className="py-3 px-4">Order ID & Defect</th>
                  <th className="py-3 px-4">Issue Description</th>
                  <th className="py-3 px-4">Location & City</th>
                  <th className="py-3 px-4">Severity</th>
                  <th className="py-3 px-4">Assigned Agency & Crew</th>
                  <th className="py-3 px-4">SLA / Target</th>
                  <th className="py-3 px-4">Status</th>
                  <th className="py-3 px-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#E2E8F0] text-xs sm:text-sm">
                {filteredOrders.length === 0 ? (
                  <tr>
                    <td colSpan={8} className="py-8 text-center text-[#64748B]">
                      No work orders match the selected filters.
                    </td>
                  </tr>
                ) : (
                  filteredOrders.map((order) => {
                    const statusBg =
                      order.status === "Completed"
                        ? "bg-[#DCFCE7] text-[#15803D] border-[#86EFAC]"
                        : order.status === "In Progress"
                        ? "bg-[#EDE9FE] text-[#6D28D9] border-[#C4B5FD]"
                        : order.status === "Assigned"
                        ? "bg-[#DBEAFE] text-[#1D4ED8] border-[#93C5FD]"
                        : "bg-[#FEF3C7] text-[#B45309] border-[#FDE68A]";

                    const sevBg =
                      order.severity === "CRITICAL"
                        ? "bg-[#FEE2E2] text-[#B91C1C]"
                        : order.severity === "HIGH"
                        ? "bg-[#FFEDD5] text-[#C2410C]"
                        : order.severity === "MEDIUM"
                        ? "bg-[#FEF9C3] text-[#A16207]"
                        : "bg-[#F1F5F9] text-[#475569]";

                    return (
                      <tr key={order.id} className="hover:bg-[#F8FAFC] transition">
                        {/* Order ID */}
                        <td className="py-3.5 px-4 font-mono font-bold text-[#0F172A] whitespace-nowrap">
                          <div className="flex items-center gap-1.5">
                            <Wrench className="w-3.5 h-3.5 text-[#2563EB]" />
                            <span>{order.id}</span>
                          </div>
                          <span className="text-[11px] font-normal text-[#64748B] block mt-0.5">
                            Ref: {order.defectId}
                          </span>
                        </td>

                        {/* Title */}
                        <td className="py-3.5 px-4 max-w-xs">
                          <span className="font-semibold text-[#1E293B] block leading-tight">
                            {order.title}
                          </span>
                          <span className="text-[11px] text-[#64748B] block mt-0.5">
                            Est: {order.estimatedCost}
                          </span>
                        </td>

                        {/* Location */}
                        <td className="py-3.5 px-4 max-w-xs">
                          <div className="flex items-center gap-1 text-[#1E293B] font-medium">
                            <MapPin className="w-3.5 h-3.5 text-[#DC2626] flex-shrink-0" />
                            <span className="truncate">{order.location}</span>
                          </div>
                          <span className="text-[11px] text-[#64748B] block ml-4">
                            {order.city}
                          </span>
                        </td>

                        {/* Severity */}
                        <td className="py-3.5 px-4 whitespace-nowrap">
                          <span className={`px-2 py-0.5 rounded text-[11px] font-bold ${sevBg}`}>
                            {order.severity}
                          </span>
                        </td>

                        {/* Agency */}
                        <td className="py-3.5 px-4 max-w-xs">
                          <span className="font-medium text-[#1E293B] block truncate">
                            {order.agency}
                          </span>
                          <span className="text-[11px] text-[#64748B] block truncate">
                            {order.assignedCrew}
                          </span>
                        </td>

                        {/* Target Completion */}
                        <td className="py-3.5 px-4 whitespace-nowrap">
                          <div className="flex items-center gap-1 text-[12px] text-[#475569]">
                            <Clock className="w-3.5 h-3.5 text-[#64748B]" />
                            <span>{order.targetCompletion}</span>
                          </div>
                        </td>

                        {/* Status */}
                        <td className="py-3.5 px-4 whitespace-nowrap">
                          <span className={`px-2.5 py-0.5 rounded-full text-xs font-semibold border ${statusBg}`}>
                            {order.status}
                          </span>
                        </td>

                        {/* Actions */}
                        <td className="py-3.5 px-4 text-right whitespace-nowrap">
                          <div className="inline-flex items-center gap-1.5">
                            <button
                              onClick={() => setSelectedOrder(order)}
                              className="px-2.5 py-1 text-xs font-medium rounded border border-[#CBD5E1] bg-white hover:bg-[#F1F5F9] text-[#1E293B] transition"
                            >
                              Inspect
                            </button>
                            <select
                              value={order.status}
                              onChange={(e) => handleUpdateStatus(order.id, e.target.value as any)}
                              className="px-2 py-1 text-xs font-medium border border-[#CBD5E1] rounded bg-white text-[#1E293B] focus:outline-none"
                            >
                              <option value="Pending">Pending</option>
                              <option value="Assigned">Assigned</option>
                              <option value="In Progress">In Progress</option>
                              <option value="Completed">Completed</option>
                            </select>
                          </div>
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* MODAL 1: Inspect Work Order Details */}
      {selectedOrder && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-2xl max-w-2xl w-full border border-[#CBD5E1] max-h-[90vh] overflow-y-auto">
            {/* Modal Header */}
            <div className="px-6 py-4 bg-[#1B254B] text-white flex items-center justify-between rounded-t-xl">
              <div className="flex items-center gap-2.5">
                <Wrench className="w-5 h-5 text-[#F59E0B]" />
                <div>
                  <h3 className="text-base font-bold">{selectedOrder.id}</h3>
                  <p className="text-xs text-[#93C5FD]">
                    Official PWD Job Card • Defect Ref {selectedOrder.defectId}
                  </p>
                </div>
              </div>
              <button
                onClick={() => setSelectedOrder(null)}
                className="text-[#94A3B8] hover:text-white p-1 rounded transition"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Modal Content */}
            <div className="p-6 space-y-5">
              <div>
                <h4 className="text-base font-bold text-[#0F172A]">{selectedOrder.title}</h4>
                <div className="flex items-center gap-2 mt-1 text-xs text-[#64748B]">
                  <MapPin className="w-3.5 h-3.5 text-[#DC2626]" />
                  <span>{selectedOrder.location} ({selectedOrder.city})</span>
                </div>
              </div>

              {/* Key Specs Grid */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-[#F8FAFC] border border-[#E2E8F0] p-3 rounded-lg text-xs">
                <div>
                  <span className="text-[#64748B] block">Severity</span>
                  <span className="font-bold text-[#DC2626]">{selectedOrder.severity}</span>
                </div>
                <div>
                  <span className="text-[#64748B] block">Current Status</span>
                  <span className="font-bold text-[#2563EB]">{selectedOrder.status}</span>
                </div>
                <div>
                  <span className="text-[#64748B] block">Target SLA</span>
                  <span className="font-bold text-[#1E293B]">{selectedOrder.targetCompletion}</span>
                </div>
                <div>
                  <span className="text-[#64748B] block">Est. Cost</span>
                  <span className="font-bold text-[#059669]">{selectedOrder.estimatedCost}</span>
                </div>
              </div>

              {/* Assignment Details */}
              <div className="space-y-2 text-xs">
                <div className="flex justify-between py-1.5 border-b border-[#E2E8F0]">
                  <span className="text-[#64748B] font-medium">Managing Civic Agency:</span>
                  <span className="font-bold text-[#1E293B]">{selectedOrder.agency}</span>
                </div>
                <div className="flex justify-between py-1.5 border-b border-[#E2E8F0]">
                  <span className="text-[#64748B] font-medium">Contractor Appointed:</span>
                  <span className="font-semibold text-[#1E293B]">{selectedOrder.contractor}</span>
                </div>
                <div className="flex justify-between py-1.5 border-b border-[#E2E8F0]">
                  <span className="text-[#64748B] font-medium">Assigned Field Unit:</span>
                  <span className="font-semibold text-[#1E293B]">{selectedOrder.assignedCrew}</span>
                </div>
                <div className="flex justify-between py-1.5 border-b border-[#E2E8F0]">
                  <span className="text-[#64748B] font-medium">Date & Time Logged:</span>
                  <span className="font-semibold text-[#1E293B]">{selectedOrder.createdAt}</span>
                </div>
              </div>

              {/* Engineering Notes */}
              <div>
                <span className="text-xs font-bold uppercase tracking-wider text-[#64748B] block mb-1">
                  Field Engineering Instructions
                </span>
                <p className="text-xs bg-[#FFFBEB] border border-[#FDE68A] p-3 rounded text-[#92400E]">
                  {selectedOrder.notes}
                </p>
              </div>

              {/* Live Timeline */}
              <div>
                <span className="text-xs font-bold uppercase tracking-wider text-[#64748B] block mb-2">
                  Action & Resolution Timeline
                </span>
                <div className="space-y-2 border-l-2 border-[#2563EB] ml-2 pl-3 text-xs">
                  {selectedOrder.timeline.map((item, idx) => (
                    <div key={idx} className="relative">
                      <div className={`absolute -left-[19px] top-0.5 w-3 h-3 rounded-full border-2 border-white ${item.done ? "bg-[#2563EB]" : "bg-[#CBD5E1]"}`} />
                      <p className={`font-semibold ${item.done ? "text-[#1E293B]" : "text-[#94A3B8]"}`}>
                        {item.step}
                      </p>
                      <span className="text-[10px] text-[#64748B]">{item.timestamp}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Status Update CTA */}
              <div className="pt-2 flex flex-wrap items-center justify-between gap-3 border-t border-[#E2E8F0]">
                <div className="flex items-center gap-2">
                  <span className="text-xs text-[#64748B] font-medium">Update Status:</span>
                  {(["Pending", "Assigned", "In Progress", "Completed"] as const).map((st) => (
                    <button
                      key={st}
                      onClick={() => handleUpdateStatus(selectedOrder.id, st)}
                      className={`px-2.5 py-1 text-xs font-semibold rounded border transition ${
                        selectedOrder.status === st
                          ? "bg-[#2563EB] text-white border-[#2563EB]"
                          : "bg-white text-[#475569] border-[#CBD5E1] hover:bg-[#F1F5F9]"
                      }`}
                    >
                      {st}
                    </button>
                  ))}
                </div>

                <button
                  onClick={() => window.print()}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-semibold bg-[#F1F5F9] hover:bg-[#E2E8F0] text-[#1E293B] transition"
                >
                  <Printer className="w-3.5 h-3.5" />
                  <span>Print Job Card</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* MODAL 2: Generate PWD Report */}
      {showReportModal && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-2xl max-w-lg w-full border border-[#CBD5E1]">
            <div className="px-6 py-4 bg-[#1B254B] text-white flex items-center justify-between rounded-t-xl">
              <div className="flex items-center gap-2.5">
                <FileText className="w-5 h-5 text-[#93C5FD]" />
                <div>
                  <h3 className="text-base font-bold">Generate PWD Compliance Report</h3>
                  <p className="text-xs text-[#93C5FD]">Ministry of Housing & Urban Affairs (MoHUA) Format</p>
                </div>
              </div>
              <button
                onClick={() => { setShowReportModal(false); setReportDownloaded(false); }}
                className="text-[#94A3B8] hover:text-white p-1 rounded transition"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="p-6 space-y-4 text-xs sm:text-sm">
              <div>
                <label className="block text-xs font-semibold text-[#475569] mb-1">
                  Target Municipal Agency / Department
                </label>
                <select
                  value={reportAgency}
                  onChange={(e) => setReportAgency(e.target.value)}
                  className="w-full px-3 py-2 border border-[#CBD5E1] rounded-md text-xs sm:text-sm text-[#1E293B] focus:outline-none focus:ring-2 focus:ring-[#2563EB]"
                >
                  <option value="ALL">All Municipal Divisions (Consolidated)</option>
                  <option value="Delhi PWD">Delhi PWD (Public Works Dept)</option>
                  <option value="BBMP">BBMP Road Infrastructure (Bengaluru)</option>
                  <option value="NHAI">NHAI Corridor Maintenance</option>
                  <option value="MCGM">MCGM Disaster & Road Dept (Mumbai)</option>
                </select>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-semibold text-[#475569] mb-1">
                    Reporting Window
                  </label>
                  <select
                    value={reportDateRange}
                    onChange={(e) => setReportDateRange(e.target.value)}
                    className="w-full px-3 py-2 border border-[#CBD5E1] rounded-md text-xs sm:text-sm text-[#1E293B] focus:outline-none focus:ring-2 focus:ring-[#2563EB]"
                  >
                    <option value="Today (Last 24h)">Today (Last 24 Hours)</option>
                    <option value="Last 7 Days">Last 7 Days</option>
                    <option value="Last 30 Days">Last 30 Days</option>
                    <option value="Quarter Q3 2026">Quarter Q3 2026</option>
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-[#475569] mb-1">
                    Work Order Status
                  </label>
                  <select
                    value={reportStatus}
                    onChange={(e) => setReportStatus(e.target.value)}
                    className="w-full px-3 py-2 border border-[#CBD5E1] rounded-md text-xs sm:text-sm text-[#1E293B] focus:outline-none focus:ring-2 focus:ring-[#2563EB]"
                  >
                    <option value="ALL">All Statuses</option>
                    <option value="Pending">Pending Only</option>
                    <option value="In Progress">In Progress</option>
                    <option value="Completed">Resolved & Closed</option>
                  </select>
                </div>
              </div>

              <div className="bg-[#F8FAFC] border border-[#E2E8F0] p-3 rounded-lg text-xs text-[#475569] space-y-1">
                <div className="flex justify-between">
                  <span>Included Work Orders:</span>
                  <span className="font-bold text-[#1E293B]">126 Total (84 Potholes, 22 Drainage, 20 Structural)</span>
                </div>
                <div className="flex justify-between">
                  <span>Verification Hash:</span>
                  <span className="font-mono text-[11px] text-[#2563EB]">SHA256: 8f4e21a...c902</span>
                </div>
                <div className="flex justify-between">
                  <span>Issuing Authority:</span>
                  <span className="font-medium text-[#1E293B]">BEL Smart Automation Command Center</span>
                </div>
              </div>

              {reportDownloaded && (
                <div className="p-3 bg-[#DCFCE7] border border-[#86EFAC] rounded-md text-xs text-[#15803D] flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 flex-shrink-0" />
                  <span>Report successfully generated and downloaded as PDF/CSV.</span>
                </div>
              )}

              <div className="pt-3 flex items-center justify-end gap-2.5">
                <button
                  type="button"
                  onClick={() => setShowReportModal(false)}
                  className="px-4 py-2 border border-[#CBD5E1] rounded-md text-xs sm:text-sm font-medium text-[#475569] hover:bg-[#F1F5F9] transition"
                >
                  Close
                </button>
                <button
                  type="button"
                  onClick={() => {
                    handleDownloadCsv();
                    setReportDownloaded(true);
                  }}
                  className="inline-flex items-center gap-2 px-4 py-2 bg-[#2563EB] hover:bg-[#1D4ED8] text-white rounded-md text-xs sm:text-sm font-semibold transition shadow-sm"
                >
                  <Download className="w-4 h-4" />
                  <span>Download Report (CSV & Summary)</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* MODAL 3: Create Manual Work Order */}
      {showNewOrderModal && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white rounded-xl shadow-2xl max-w-md w-full border border-[#CBD5E1]">
            <div className="px-6 py-4 bg-[#1B254B] text-white flex items-center justify-between rounded-t-xl">
              <div className="flex items-center gap-2.5">
                <Plus className="w-5 h-5 text-[#F59E0B]" />
                <h3 className="text-base font-bold">Dispatch New PWD Work Order</h3>
              </div>
              <button
                onClick={() => setShowNewOrderModal(false)}
                className="text-[#94A3B8] hover:text-white p-1 rounded transition"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleCreateWorkOrder} className="p-6 space-y-4 text-xs sm:text-sm">
              <div>
                <label className="block text-xs font-semibold text-[#475569] mb-1">
                  Work Order Title / Defect Scope *
                </label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Ring Road KM 12 Deep Pothole Repair"
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  className="w-full px-3 py-2 border border-[#CBD5E1] rounded-md text-xs sm:text-sm text-[#1E293B] focus:outline-none focus:ring-2 focus:ring-[#2563EB]"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-[#475569] mb-1">
                  Location / Highway Corridor *
                </label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Outer Ring Road, Near Gate 3"
                  value={newLocation}
                  onChange={(e) => setNewLocation(e.target.value)}
                  className="w-full px-3 py-2 border border-[#CBD5E1] rounded-md text-xs sm:text-sm text-[#1E293B] focus:outline-none focus:ring-2 focus:ring-[#2563EB]"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-semibold text-[#475569] mb-1">
                    Civic Agency
                  </label>
                  <select
                    value={newAgency}
                    onChange={(e) => setNewAgency(e.target.value)}
                    className="w-full px-3 py-2 border border-[#CBD5E1] rounded-md text-xs sm:text-sm text-[#1E293B] focus:outline-none focus:ring-2 focus:ring-[#2563EB]"
                  >
                    <option value="Delhi PWD">Delhi PWD</option>
                    <option value="BBMP Bengaluru">BBMP Bengaluru</option>
                    <option value="NHAI Western Corridor">NHAI Highways</option>
                    <option value="MCGM Mumbai">MCGM Mumbai</option>
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-[#475569] mb-1">
                    Severity Priority
                  </label>
                  <select
                    value={newSeverity}
                    onChange={(e) => setNewSeverity(e.target.value as any)}
                    className="w-full px-3 py-2 border border-[#CBD5E1] rounded-md text-xs sm:text-sm text-[#1E293B] focus:outline-none focus:ring-2 focus:ring-[#2563EB]"
                  >
                    <option value="CRITICAL">Critical (Within 6h)</option>
                    <option value="HIGH">High (Within 12h)</option>
                    <option value="MEDIUM">Medium (Within 24h)</option>
                    <option value="LOW">Low (Within 48h)</option>
                  </select>
                </div>
              </div>

              <div className="pt-3 flex items-center justify-end gap-2.5">
                <button
                  type="button"
                  onClick={() => setShowNewOrderModal(false)}
                  className="px-4 py-2 border border-[#CBD5E1] rounded-md text-xs sm:text-sm font-medium text-[#475569] hover:bg-[#F1F5F9] transition"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 bg-[#2563EB] hover:bg-[#1D4ED8] text-white rounded-md text-xs sm:text-sm font-semibold transition shadow-sm"
                >
                  Issue Work Order
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default WorkOrders;
