// src/pages/RoadDefects/mockData.ts
// Realistic demo data for Road Defect Management (Phase 18)

import { DefectEvent, DefectSummary } from "./types";

export const MOCK_EVENTS: DefectEvent[] = [
  {
    defect_id: "DEF-2026-001",
    event_id: "DEF-2026-001",
    event_type: "road_defect",
    cls: "pothole",
    type: "POTHOLE",
    label: "Pothole (Depth 7.5cm)",
    confidence: 0.942,
    severity: "HIGH",
    road_segment: "CP_INNER_CIRCLE",
    bounding_box: [120, 300, 220, 380],
    camera_id: "FRONT",
    bus_id: "BUS_001",
    timestamp: new Date(Date.now() - 3600_000 * 2).toISOString(),
    first_detected: new Date(Date.now() - 86400_000 * 2).toISOString(),
    last_detected: new Date(Date.now() - 3600_000 * 2).toISOString(),
    buses_confirming: ["BUS_001", "BUS_002", "BUS_007"],
    number_of_buses_confirming: 3,
    detection_count: 18,
    assigned_authority: "Public Works Department (PWD)",
    priority_score: 88,
    priority_breakdown: {
      severity_score: 75.0,
      traffic_volume_score: 100.0,
      detections_score: 95.0,
      location_importance_score: 85.0,
      safety_risk_score: 90.0,
      persistence_score: 60.0,
      total_priority_score: 88,
      priority_tier: "CRITICAL",
    },
    gps: {
      lat: 28.6335,
      lon: 77.2195,
      bearing_deg: 45,
      address: "Connaught Place Radial Rd 2",
      district: "Central",
    },
    status: "CONFIRMED",
    audit_history: [
      {
        timestamp: new Date(Date.now() - 86400_000 * 2).toISOString(),
        actor: "BUS_001",
        action: "INITIAL_DETECTION",
        from_status: "NONE",
        to_status: "AI_DETECTED",
      },
      {
        timestamp: new Date(Date.now() - 86400_000 * 1).toISOString(),
        actor: "FLEET_CONSENSUS",
        action: "MULTI_BUS_CONFIRM",
        from_status: "AI_DETECTED",
        to_status: "CONFIRMED",
        notes: "3 distinct buses confirmed pothole signature.",
      },
    ],
  },
  {
    defect_id: "DEF-2026-002",
    event_id: "DEF-2026-002",
    event_type: "road_defect",
    cls: "damaged_road",
    type: "DAMAGED_ROAD",
    label: "Alligator Surface Cracking",
    confidence: 0.915,
    severity: "HIGH",
    road_segment: "RING_ROAD_AIIMS",
    bounding_box: [0, 400, 640, 460],
    camera_id: "FRONT",
    bus_id: "BUS_003",
    timestamp: new Date(Date.now() - 3600_000 * 5).toISOString(),
    first_detected: new Date(Date.now() - 86400_000 * 3).toISOString(),
    last_detected: new Date(Date.now() - 3600_000 * 5).toISOString(),
    buses_confirming: ["BUS_001", "BUS_003", "BUS_004", "BUS_008"],
    number_of_buses_confirming: 4,
    detection_count: 24,
    assigned_authority: "National Highways Authority of India (NHAI)",
    maintenance_ticket: {
      ticket_id: "TICK-2026-N102",
      assigned_authority: "National Highways Authority of India (NHAI)",
      assigned_contractor: "Larsen & Toubro Infra",
      target_completion_date: "2026-09-20",
      work_order_notes: "Asphalt milling and resurfacing of 12m section.",
      created_at: new Date(Date.now() - 86400_000 * 1).toISOString(),
      status: "ASSIGNED",
    },
    priority_score: 82,
    priority_breakdown: {
      severity_score: 75.0,
      traffic_volume_score: 100.0,
      detections_score: 100.0,
      location_importance_score: 100.0,
      safety_risk_score: 65.0,
      persistence_score: 80.0,
      total_priority_score: 82,
      priority_tier: "CRITICAL",
    },
    gps: {
      lat: 28.5680,
      lon: 77.2090,
      bearing_deg: 92,
      address: "Ring Road Flyover Ramp near AIIMS",
      district: "South",
    },
    status: "ASSIGNED",
  },
  {
    defect_id: "DEF-2026-003",
    event_id: "DEF-2026-003",
    event_type: "road_defect",
    cls: "waterlogging",
    type: "WATERLOGGING",
    label: "Underpass Waterlogging (Depth 15cm)",
    confidence: 0.884,
    severity: "MEDIUM",
    road_segment: "TOLSTOY_MARG",
    bounding_box: [45, 345, 255, 425],
    camera_id: "FRONT",
    bus_id: "BUS_001",
    timestamp: new Date(Date.now() - 3600_000 * 1).toISOString(),
    first_detected: new Date(Date.now() - 86400_000 * 1).toISOString(),
    last_detected: new Date(Date.now() - 3600_000 * 1).toISOString(),
    buses_confirming: ["BUS_001", "BUS_005"],
    number_of_buses_confirming: 2,
    detection_count: 12,
    assigned_authority: "New Delhi Municipal Council (NDMC)",
    maintenance_ticket: {
      ticket_id: "TICK-2026-M103",
      assigned_authority: "New Delhi Municipal Council (NDMC)",
      assigned_contractor: "Civic Drainage Works",
      target_completion_date: "2026-09-17",
      work_order_notes: "Drain clearing & sump pump installation.",
      created_at: new Date(Date.now() - 3600_000 * 12).toISOString(),
      status: "UNDER_REPAIR_50%",
    },
    priority_score: 76,
    priority_breakdown: {
      severity_score: 45.0,
      traffic_volume_score: 80.0,
      detections_score: 75.0,
      location_importance_score: 65.0,
      safety_risk_score: 85.0,
      persistence_score: 60.0,
      total_priority_score: 76,
      priority_tier: "HIGH",
    },
    gps: {
      lat: 28.6280,
      lon: 77.2260,
      bearing_deg: 180,
      address: "Tolstoy Marg Underpass",
      district: "Central",
    },
    status: "UNDER_REPAIR",
  },
  {
    defect_id: "DEF-2026-004",
    event_id: "DEF-2026-004",
    event_type: "road_defect",
    cls: "pothole",
    type: "POTHOLE",
    label: "Recurring Pothole (Post-Closure Recurrence)",
    confidence: 0.963,
    severity: "SEVERE",
    road_segment: "MG_ROAD_CORRIDOR",
    bounding_box: [110, 310, 240, 390],
    camera_id: "FRONT",
    bus_id: "BUS_002",
    timestamp: new Date(Date.now() - 1800_000).toISOString(),
    first_detected: new Date(Date.now() - 86400_000 * 7).toISOString(),
    last_detected: new Date(Date.now() - 1800_000).toISOString(),
    buses_confirming: ["BUS_002", "BUS_006", "BUS_009", "BUS_011"],
    number_of_buses_confirming: 4,
    detection_count: 32,
    assigned_authority: "Bruhat Bengaluru Mahanagara Palike (BBMP)",
    maintenance_ticket: {
      ticket_id: "TICK-2026-B104",
      assigned_authority: "Bruhat Bengaluru Mahanagara Palike (BBMP)",
      assigned_contractor: "Karnataka Urban Roadways",
      target_completion_date: "2026-09-12",
      work_order_notes: "Cold mix asphalt patching applied.",
      created_at: new Date(Date.now() - 86400_000 * 5).toISOString(),
      status: "REOPENED_AFTER_CLOSURE",
    },
    repair_evidence: {
      evidence_id: "EVID-2026-004",
      before_image_b64: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWPjfDwAEfQHzgV23vAAAAABJRU5ErkJggg==",
      after_image_b64: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkWPjfDwAEfQHzgV23vAAAAABJRU5ErkJggg==",
      completion_notes: "Patched on Sep 12. Asphalt washed away after heavy rain.",
      engineer_id: "ENG_CONTRACTOR_09",
      uploaded_at: new Date(Date.now() - 86400_000 * 3).toISOString(),
      completion_certificate_url: "/certs/cert_bbmp_2026_0912.pdf",
    },
    closed_at: new Date(Date.now() - 86400_000 * 3).toISOString(),
    closed_by: "ENG_SUPERVISOR_007",
    reopened_at: new Date(Date.now() - 86400_000 * 1).toISOString(),
    reopen_reason: "Transit bus BUS_009 re-detected recurring pothole at MG Road Metro Pillar 142 after official closure.",
    reopen_count: 1,
    priority_score: 94,
    priority_breakdown: {
      severity_score: 100.0,
      traffic_volume_score: 100.0,
      detections_score: 100.0,
      location_importance_score: 85.0,
      safety_risk_score: 95.0,
      persistence_score: 95.0,
      total_priority_score: 94,
      priority_tier: "CRITICAL",
    },
    gps: {
      lat: 12.9730,
      lon: 77.6000,
      bearing_deg: 88,
      address: "MG Road Metro Pillar 142",
      district: "CBD",
    },
    status: "REOPENED_UNDER_REVIEW",
    audit_history: [
      {
        timestamp: new Date(Date.now() - 86400_000 * 3).toISOString(),
        actor: "ENG_SUPERVISOR_007",
        action: "CLOSE_MAINTENANCE_TICKET",
        from_status: "UNDER_REPAIR",
        to_status: "RESOLVED",
        notes: "Initial repair completed and verified.",
      },
      {
        timestamp: new Date(Date.now() - 86400_000 * 1).toISOString(),
        actor: "AUTONOMOUS_WATCHDOG_BUS_009",
        action: "REOPEN_AFTER_CLOSURE",
        from_status: "RESOLVED",
        to_status: "REOPENED_UNDER_REVIEW",
        notes: "Transit bus surveillance detected recurrence at exact coordinates. Flagged for quality audit.",
      },
    ],
  },
  {
    defect_id: "DEF-2026-005",
    event_id: "DEF-2026-005",
    event_type: "road_defect",
    cls: "pothole",
    type: "POTHOLE",
    label: "Resolved Pothole (Watchdog Ready)",
    confidence: 0.880,
    severity: "LOW",
    road_segment: "MARINE_DRIVE_ARTERIAL",
    camera_id: "FRONT",
    bus_id: "BUS_003",
    timestamp: new Date(Date.now() - 86400_000 * 5).toISOString(),
    first_detected: new Date(Date.now() - 86400_000 * 10).toISOString(),
    last_detected: new Date(Date.now() - 86400_000 * 5).toISOString(),
    buses_confirming: ["BUS_003"],
    number_of_buses_confirming: 1,
    detection_count: 8,
    assigned_authority: "Brihanmumbai Municipal Corporation (BMC)",
    maintenance_ticket: {
      ticket_id: "TICK-2026-BMC105",
      assigned_authority: "Brihanmumbai Municipal Corporation (BMC)",
      created_at: new Date(Date.now() - 86400_000 * 9).toISOString(),
      status: "RESOLVED",
    },
    closed_at: new Date(Date.now() - 86400_000 * 5).toISOString(),
    closed_by: "ENG_SUPERVISOR_007",
    priority_score: 42,
    priority_breakdown: {
      severity_score: 20.0,
      traffic_volume_score: 55.0,
      detections_score: 45.0,
      location_importance_score: 65.0,
      safety_risk_score: 50.0,
      persistence_score: 30.0,
      total_priority_score: 42,
      priority_tier: "MEDIUM",
    },
    gps: {
      lat: 18.9480,
      lon: 72.8235,
      bearing_deg: 12,
      address: "Marine Drive Promenade Bay 4",
      district: "South",
    },
    status: "RESOLVED",
  },
  {
    defect_id: "DEF-2026-006",
    event_id: "DEF-2026-006",
    event_type: "road_defect",
    cls: "missing_road_divider",
    type: "MISSING_DIVIDER",
    label: "Missing Concrete Median Divider",
    confidence: 0.845,
    severity: "MEDIUM",
    road_segment: "JANPATH_RD",
    camera_id: "FRONT",
    bus_id: "BUS_001",
    timestamp: new Date().toISOString(),
    first_detected: new Date().toISOString(),
    last_detected: new Date().toISOString(),
    buses_confirming: ["BUS_001"],
    number_of_buses_confirming: 1,
    detection_count: 2,
    priority_score: 71,
    priority_breakdown: {
      severity_score: 45.0,
      traffic_volume_score: 80.0,
      detections_score: 30.0,
      location_importance_score: 65.0,
      safety_risk_score: 95.0,
      persistence_score: 30.0,
      total_priority_score: 71,
      priority_tier: "HIGH",
    },
    gps: {
      lat: 28.6265,
      lon: 77.2210,
      bearing_deg: 270,
      address: "Janpath Road Cross Junction",
      district: "Central",
    },
    status: "UNVERIFIED",
  },
];

export const MOCK_SUMMARY: DefectSummary = {
  total: 6,
  by_class: {
    pothole: 3,
    damaged_road: 1,
    waterlogging: 1,
    missing_road_divider: 1,
  },
  by_severity: {
    CRITICAL: 2,
    HIGH: 2,
    MEDIUM: 1,
    LOW: 1,
  },
  by_status: {
    AI_DETECTED: 0,
    UNVERIFIED: 1,
    CONFIRMED: 1,
    ASSIGNED: 1,
    UNDER_REPAIR: 1,
    RESOLVED: 1,
    REOPENED_UNDER_REVIEW: 1,
    REJECTED: 0,
  },
};
